# All strings can include colour codes using & unless otherwise stated

# Whether or not to save games through reboots
persistantSave: false

# Sets the size of the world borders (must be a number, can have a decimal)
worldborder:
  overworld: 4000
  nether: 4000
  end: 500

# The title for the scoreboard (must be under 128 characters)
title: "&6domain.name"

# Sets the minimum number of players for a game to automaticaly start (also used for the player number in the scoreboard)
minPlayers: 5

# These settings regaurd the game itself
game:
  # The time a runner gets before the hunters are moved to the world
  headStart: 5
  # The period of time between each location reveal
  locationRevealTime: 2