name: SpeedrunnerVsHunters
version: 0.7
description: The plugin to run the logic for the speedrunner vs hunters Minecraft gamemode.
main: me.RedTheITGuy.SpeedrunnerVsHunters.Main
api-version: 1.16
author: Red_the_IT_Guy
load: POSTWORLD
commands:
  startgame:
    description: Start a round of Speedrunner vs Hunters
    usage: "/startgame <player-name>"
    permission: svh.startgame

permissions:
  svh.startgame:
    description: Allows the player to start a game of Speedrunner vs Hunters
    default: op